checkForUpdatesAutomatically: false
showFloatingNotifications: true
showMenuBarTitle: true
showMenuBarIcon: true
menuBarTitleTemplate: $WORKSPACE
menuBarDisplayAliases: ''
enableFocusManagement: true
centerCursorOnFocusChange: false
focusLeft: opt+h
focusRight: opt+l
focusUp: opt+k
focusDown: opt+j
focusFrontmostWindow: false
enableSwipeGestures: true
swipeThreshold: 1e-1
restartAppOnWakeUp: true
swipeLeft3FingerAction: none
swipeRight3FingerAction: none
swipeUp3FingerAction: none
swipeDown3FingerAction: none
swipeLeft4FingerAction: nextWorkspace
swipeRight4FingerAction: previousWorkspace
swipeUp4FingerAction: none
swipeDown4FingerAction: none
displayMode: static
centerCursorOnWorkspaceChange: true
changeWorkspaceOnAppAssign: true
activeWorkspaceOnFocusChange: true
autoAssignAppsToWorkspaces: false
autoAssignAlreadyAssignedApps: false
skipEmptyWorkspacesOnSwitch: false
keepUnassignedAppsOnSwitch: false
restoreHiddenAppsOnSwitch: true
enableWorkspaceTransitions: false
showRecentWorkspaceWhenActivatedTwice: false
workspaceTransitionDuration: 3e-1
workspaceTransitionDimming: 2e-1
loopWorkspaces: true
loopWorkspacesOnAllDisplays: false
switchWorkspaceOnCursorScreen: false
alternativeDisplays: ''
enablePictureInPictureSupport: true
switchWorkspaceWhenPipCloses: true
pipApps: []
pipScreenCornerOffset: 15
cornerHiddenApps: []
enableSpaceControl: false
enableSpaceControlAnimations: true
enableSpaceControlTilesAnimations: true
spaceControlCurrentDisplayWorkspaces: false
spaceControlHideEmptyWorkspaces: false
spaceControlUpdateScreenshotsOnOpen: false
spaceControlNumberOfColumns: 0
enableIntegrations: false
runScriptOnLaunch: ''
runScriptOnWorkspaceChange: sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE"
  DISPLAY="$DISPLAY"
runScriptAfterWorkspaceChange: ''
runScriptOnProfileChange: sketchybar --reload
